services:
  # NO SE PUEDE LEVANTAR EL BOT DE TELEGRAM EN EL MISMO SERVER QUE EL SERVER DE MINECRAFT 🔥
  # servercito:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3333:3333'
  #   environment:
  #     BOT_TOKEN: 'your-bot-token'
  #     GIPHY_TOKEN: 'your-giphy-token'
  #     SERVER_GCP_ZONE: 'your-gcp-zone'
  #     SERVER_GCP_NAME: 'your-server-name'
  #   volumes:
  #     - ./my_credentials.json:/app/my_credentials.json
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - '25565:25565'
    restart: unless-stopped
    env_file:
      - minecraft.env
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    ports:
      - 8080:80
    volumes:
      - ./minecraft.env:/srv/minecraft.env # Mounting the Minecraft environment file for file access in FileBrowser
      - ./data:/srv # Mounting the Minecraft data directory for file access in FileBrowser
      - ./filebrowser-data:/data # Persistent storage for FileBrowser settings and database
      - ./filebrowser-config:/config # Configuration storage for FileBrowser
    environment:
      - TZ='America/Argentina/Buenos_Aires'
      - FB_BASEURL=/filebrowser
    restart: unless-stopped
