version: '3.8'

services:
  servercito:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    environment:
      BOT_TOKEN: 'your-bot-token'
      GIPHY_TOKEN: 'your-giphy-token'
    volumes:
      - .:/app
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - '25565:25565'
    restart: unless-stopped
    environment:
      EULA: 'TRUE'
      SERVER_NAME: 'elserverdelospiolas'
      MOTD: 'ola wuachines'
      MODE: 'survival'
      ENABLE_RCON: 'true'
      RCON_PASSWORD: password
      RCON_PORT: 28016
      SERVER_PORT: 25565
      ENABLE_WHITELIST: 'true'
      MAX_PLAYERS: 20
      PVP: 'true'
      TZ: 'America/Argentina/Buenos_Aires'
      MODS_FILE: /extras/mods.txt
      REMOVE_OLD_MODS: 'true'
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
